# Generated by Django 4.1.6 on 2023-02-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
