# Generated by Django 4.0.6 on 2023-02-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_stu_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
